### ISSUE TITLE
How do I plot updates that I upload in Jupyter. 

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3dpy-notebooks#12]
The Wolf Pass notebook updates the scene in stages adding the boreholes after the surface. Since I am having issues zooming into the scene outside of jupyter, What command do I use to update the scene within Jupyter?

I assume it  some_object.plot() or steno3d.plot(url)?

**Comment by fwkoch** [comment]
@hal98x -

In versions <= 0.2.7, inline plotting was only available for individual components (eg. `my_point.plot()`, `my_surf.plot()`). However, I just released a small update (v0.2.8) that now allows inline plotting of projects (ie. `my_proj.plot()` or in the case of the Wolf Pass notebook, `prelim_data.plot()`). As you add different features to the scene, the plotted project should update automatically (or you can simply call `my_proj.plot()` again).

`pip install --upgrade steno3d` should get you v0.2.8. If this new project `plot` function doesn't do the trick, or if you have any followup questions/suggestions, let us know.

Regarding zooming issues, we managed to recreate this problem when using a specific trackpad and Microsoft Edge browser. It seems to be a picky issue, as different browsers work with the same trackpad and different mice work with Edge. Anyway, hopefully we will close in on a fix soon.

**Comment by hal98x** [comment]
Thanks for the update to steno this works well. Also thank you for an update on the zooming issue.
