### ISSUE TITLE
Keychain Backend on Binders

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/steno3dpy-notebooks#2]
The backend for the keychain saver (for the developer key) is not able to be initiated in the binders environment. Can we throw that is a try-catch block and ask for input that is stored in the session memory. That means if you restart the kernel you will need to re-input your key.

![image](https://cloud.githubusercontent.com/assets/913249/16778106/0c401ee2-4832-11e6-9b9c-c24587fddd15.png)

**Comment by fwkoch** [comment]
<img width="1094" alt="screen shot 2016-07-12 at 4 06 39 pm" src="https://cloud.githubusercontent.com/assets/9453731/16785381/f57abce4-484a-11e6-94b2-c68896dda8ea.png">
